-- Migration number: 0004 	 2024-10-28T13:10:49.124Z
DROP TABLE IF EXISTS tags;
CREATE TABLE IF NOT EXISTS tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    pageIdDict TEXT NOT NULL DEFAULT '{}',
    color TEXT NOT NULL DEFAULT '#FFFFFF',
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tags_id ON tags(id);
CREATE INDEX IF NOT EXISTS idx_tags_name ON tags(name);
